# Create IAM binding between K8s ServiceAccount and GCP ServiceAccount
#
# gcloud iam service-accounts add-iam-policy-binding $CLUSTER_SERVICE_ACCOUNT \
#   --role roles/iam.workloadIdentityUser \
#   --member "serviceAccount:$PROJECT_ID.svc.id.goog[$KSA_NAMESPACE/$KSA_NAME]"
#
# NOTE: this needs to be done BEFORE creating the k8s service account below

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cross-encoder-sa
  namespace: cross-encoder
  annotations:
    iam.gke.io/gcp-service-account: node-sa@poc-data-platform-289915.iam.gserviceaccount.com
